# Generated by Django 5.1.6 on 2025-03-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='student_images/'),
        ),
    ]
